name: Blog Posts
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update Profile With Latest Blog Posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/krishdevdb,https://medium.com/feed/@krishdevdb,https://stackoverflow.com/feeds/user/15149214,https://meta.stackexchange.com/feeds/user/953765,https://www.youtube.com/feeds/videos.xml?channel_id=UCEGVotKwGg-P-Ul2m9_GHaw,https://krishdevdb.hashnode.dev/rss.xml"
          max_post_count: 2
          gh_token: ${{ secrets.token }}
          comment_tag_name: BLOG-POSTS
          committer_username: krishdevdb
          committer_email: krishdevdb@gmail.com
          enable_keepalive: false