name: Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  blog:
    name: Update Profile With Latest Blog Posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/krishdevdb,https://medium.com/feed/@krishdevdb,https://stackoverflow.com/feeds/user/15149214,https://meta.stackexchange.com/feeds/user/953765,https://krishdevdb.hashnode.dev/rss.xml"
          max_post_count: 2
          gh_token: ${{ secrets.token }}
          comment_tag_name: BLOG-POSTS
          commit_message: 'Update Profile With Latest Blog Posts'
          committer_username: krishdevdb
          committer_email: krishdevdb@gmail.com
          enable_keepalive: false
  breakdown:
    name: Update Profile With Weekly Development Breakdown
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.waka_api }}
          GH_TOKEN: ${{ secrets.token }}
          COMMIT_MESSAGE: 'Update Profile With Weekly Development Breakdown'
  activity:
    name: Update Profile With Recent Activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          COMMIT_MSG: 'Update Profile With Recent Activity'
  snake:
    name: Snake Gif At Bottom
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v0.0.18
        with:
          github_user_name: krishdevdb
          gif_out_path: ./images/snake.gif
