name: Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  blog:
    name: Update Profile With Latest Blog Posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/krishdevdb,https://medium.com/feed/@krishdevdb,https://krishdevdb.hashnode.dev/rss.xml"
          max_post_count: 2
          gh_token: ${{ secrets.token }}
          comment_tag_name: BLOG-POSTS
          commit_message: 'Update Profile With Latest Blog Posts'
          committer_username: krishdevdb
          committer_email: krishdevdb@gmail.com
          enable_keepalive: false
  breakdown:
    name: Update Profile With Weekly Development Breakdown
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.waka_api }}
          GH_TOKEN: ${{ secrets.token }}
          COMMIT_MESSAGE: 'Update Profile With Weekly Development Breakdown'
  activity:
    name: Update Readme With Activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          template: "templates/README.md.template"
          writeTo: "README.md"

      - uses: actions/upload-artifact@v1
        with:
          name: README.md
          path: README.md

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          commit_message: Update With Activity
          branch: master
          commit_user_name: krishdevdb
          commit_user_email: krishdevdb@gmail.com
          commit_author: krishdevdb <krishdevdb@gmail.com>
  
