name: Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  activity:
    name: Update Readme With Activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          template: "README.md.template"
          writeTo: "README.md"

      - uses: actions/upload-artifact@v1
        with:
          name: README.md
          path: README.md

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          commit_message: Update With Activity
          branch: master
          commit_user_name: krishdevdb
          commit_user_email: krishdevdb@gmail.com
          commit_author: krishdevdb <krishdevdb@gmail.com>
  breakdown:
    name: Update Profile With Weekly Development Breakdown
    runs-on: ubuntu-latest
    needs: activity
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.waka_api }}
          GH_TOKEN: ${{ secrets.token }}
          COMMIT_MESSAGE: 'Update Profile With Weekly Development Breakdown'
  
